LATEX=pdflatex

presentacion: presentacion.tex
	$(LATEX) presentacion.tex 
	$(LATEX) presentacion.tex
	$(LATEX) presentacion.tex
clean:
	rm -f *.toc *.aux *.nav *.log *.snm *.out *~

cleanall: clean
	rm -f *.pdf *.dvi
