#! /bin/sh -e
set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/home/mswl/bin/battery_meter.sh
NAME=battery-meter-daemon
EXECNAME=/bin/bash
PIDFILE=/var/run/battery_meter.pid
DESCRIPTION="Battery meter"

test -x $DAEMON || exit 0

case "$1" in
    start)
        logger "Starting $DESCRIPTION"
        start-stop-daemon -S -b -p $PIDFILE -x $EXECNAME $DAEMON
    ;;
  stop)
        logger "Stopping $DESCRIPTION"
        start-stop-daemon -K -p $PIDFILE -x $EXECNAME $DAEMON
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0

